# !!!NOTE: run this from the compose.sh script!!!
#
# This will start a code-server container and expose it at http://127.0.0.1:8080.
# It will also mount your current directory into the container as `/home/coder/project`
# and forward your UID/GID so that all file system operations occur as your user outside
# the container.
#
# Your $HOME/.config is mounted at $HOME/.config within the container to ensure you can
# easily access/modify your code-server config in $HOME/.config/code-server/config.json
# outside the container.

services:
  code-server:
    image: jholtsmith/code-server-node:latest
    container_name: code-server
    environment:
      - DOCKER_USER=${USER}
      - TZ=Europe/London
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      # - DEFAULT_WORKSPACE=/config/workspace #optional
    user: ${PUID}:${PGID}
    volumes:
      - ${HOME}/.config:/home/coder/.config
      - ${PWD}/..:/home/coder/project
    ports:
      - 8080:8080
    restart: unless-stopped